; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:attiny85]
platform = atmelavr
board = attiny85
framework = arduino

; 1. Set the software clock speed
board_build.f_cpu = 8000000L

; 2. Programmer settings
upload_protocol = usbasp
upload_flags =
    -B32

; 3. Hardware Fuse Settings (for Internal 8MHz)
board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFF

; 2. Change hardware fuse back to factory default (1MHz)
; board_fuses.lfuse = 0x62
; board_fuses.hfuse = 0xDF
; board_fuses.efuse = 0xFF
;board_build.f_cpu = 1000000L

;click Burn Bootloader (or Set Fuses)